Values Schema and default value for DRONE_SERVER_HOST blocks CI testing
CI fails to pass because values.yaml contains an invalid null string.

Running 'helm lint ./drone' fails

Even calling helm lint with an additional
'-f ./drone/ci/test-values.yaml' still fails to validate values.yaml

    $  helm lint ./drone/ -f ./drone/ci/test-values.yaml
    ==> Linting ./drone/
    [ERROR] values.yaml: - env.DRONE_SERVER_HOST: String length must be greater than or equal to 3

    Error: 1 chart(s) linted, 1 chart(s) failed

I have updated values.yaml with the example string used in the drone
documentation page for the DRONE_SERVER_HOST value:

https://readme.drone.io/server/reference/drone-server-host/